import {useEffect,useState,type FormEvent} from 'react';
import{LayoutDashboard,Users,ReceiptText,WalletCards,Settings,LogOut,Plus,Repeat2,Link2,ArrowUpRight}from'lucide-react';
import{api,token}from'./api';
import type{Summary,Customer,Payment,Subscription,PaymentLink,Transfer}from'./types';
import{Dashboard,Customers,Payments,Subscriptions,PaymentLinks,Transfers,Finance,SettingsPanel}from'./pages';
import{CustomerModal,PaymentModal,SubscriptionModal,PaymentLinkModal}from'./components/Forms';
type ModalName='customer'|'payment'|'subscription'|'paymentLink'|null;
export default function App(){
 const[logged,setLogged]=useState(!!token());const[tab,setTab]=useState('dashboard');const[sum,setSum]=useState<Summary|null>(null);const[customers,setCustomers]=useState<Customer[]>([]);const[payments,setPayments]=useState<Payment[]>([]);const[subscriptions,setSubscriptions]=useState<Subscription[]>([]);const[paymentLinks,setPaymentLinks]=useState<PaymentLink[]>([]);const[transfers,setTransfers]=useState<Transfer[]>([]);const[modal,setModal]=useState<ModalName>(null);const[msg,setMsg]=useState('');
 const logout=()=>{localStorage.removeItem('getway_token');setLogged(false)};
 const load=async()=>{if(!logged)return;try{const[s,c,p,sub,links,trf]=await Promise.all([api<Summary>('/api/dashboard'),api<Customer[]>('/api/customers'),api<Payment[]>('/api/payments'),api<Subscription[]>('/api/subscriptions'),api<PaymentLink[]>('/api/payment-links'),api<Transfer[]>('/api/transfers')]);setSum(s);setCustomers(c);setPayments(p);setSubscriptions(sub);setPaymentLinks(links);setTransfers(trf)}catch(e){if(e instanceof Error&&e.message.includes('Token'))logout()}};
 useEffect(()=>{void load()},[logged]);
 if(!logged)return <Login onLogin={()=>setLogged(true)}/>;
 const nav=[['dashboard','Visão geral',LayoutDashboard],['customers','Clientes',Users],['payments','Cobranças',ReceiptText],['subscriptions','Assinaturas',Repeat2],['links','Links de pagamento',Link2],['transfers','Transferências',ArrowUpRight],['finance','Financeiro',WalletCards],['settings','Configurações',Settings]] as const;
 const openPrimary=()=>setModal(tab==='customers'?'customer':tab==='subscriptions'?'subscription':tab==='links'?'paymentLink':'payment');
 const primaryLabel=tab==='customers'?'Novo cliente':tab==='subscriptions'?'Nova assinatura':tab==='links'?'Novo link':'Nova cobrança';
 const done=()=>{setModal(null);void load()};const copied=(text:string,label:string)=>{void navigator.clipboard.writeText(text);setMsg(label);setTimeout(()=>setMsg(''),1800)};
 return <div className="shell"><aside><div className="brand"><div className="logo">G</div><div><b>Getway</b><span>PAYMENTS</span></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}</nav><button className="logout" onClick={logout}><LogOut size={18}/>Sair</button></aside><main><header><div><p>Central financeira</p><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div>{!['transfers','finance','settings'].includes(tab)&&<button className="primary" onClick={openPrimary}><Plus size={17}/>{primaryLabel}</button>}</header>{msg&&<div className="toast">{msg}</div>}{tab==='dashboard'&&<Dashboard sum={sum} payments={payments}/>} {tab==='customers'&&<Customers data={customers}/>} {tab==='payments'&&<Payments data={payments} onCopy={v=>copied(v,'Pix copiado')}/>} {tab==='subscriptions'&&<Subscriptions data={subscriptions}/>} {tab==='links'&&<PaymentLinks data={paymentLinks} onCopy={v=>copied(v,'Link copiado')}/>} {tab==='transfers'&&<Transfers data={transfers}/>} {tab==='finance'&&<Finance sum={sum}/>} {tab==='settings'&&<SettingsPanel/>}{modal==='customer'&&<CustomerModal close={()=>setModal(null)} done={done}/>} {modal==='payment'&&<PaymentModal customers={customers} close={()=>setModal(null)} done={done}/>} {modal==='subscription'&&<SubscriptionModal customers={customers} close={()=>setModal(null)} done={done}/>} {modal==='paymentLink'&&<PaymentLinkModal close={()=>setModal(null)} done={done}/>}</main></div>
}
function Login({onLogin}:{onLogin:()=>void}){const[email,setEmail]=useState('demo@getway.local');const[password,setPassword]=useState('Getway@123');const[err,setErr]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{const r=await api<{token:string}>('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('getway_token',r.token);onLogin()}catch(e){setErr(e instanceof Error?e.message:'Falha ao entrar')}};return <div className="login"><form onSubmit={submit}><div className="loginBrand"><div className="logo">G</div><h1>Getway Pay</h1></div><p>Acesse sua central financeira</p><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<small className="error">{err}</small>}<button className="primary">Entrar</button><small>Ambiente inicial: use o usuário criado pelo seed.</small></form></div>}
