import {Copy,Search,CheckCircle2} from 'lucide-react';
import type {Customer,Payment,PaymentLink,Subscription,Summary,Transfer} from './types';
import {money} from './utils';
export function Dashboard({sum,payments}:{sum:Summary|null,payments:Payment[]}){return <><section className="cards"><Card label="Saldo recebido" value={money(sum?.balance||0)}/><Card label="A receber" value={money(sum?.pending||0)}/><Card label="Em atraso" value={money(sum?.overdue||0)}/><Card label="Cobranças" value={String(sum?.payments||0)}/></section><section className="panel"><div className="panelHead"><div><h2>Últimas cobranças</h2><p>Acompanhe seus recebimentos em tempo real.</p></div></div><PaymentTable data={payments.slice(0,7)}/></section></>}
function Card({label,value}:{label:string,value:string}){return <div className="card"><span>{label}</span><strong>{value}</strong><small>Atualizado agora</small></div>}
export function Customers({data}:{data:Customer[]}){return <section className="panel"><div className="panelHead"><div><h2>Clientes</h2><p>{data.length} cadastrados</p></div><div className="search"><Search size={16}/><input placeholder="Buscar cliente"/></div></div><table><thead><tr><th>Cliente</th><th>E-mail</th><th>ID</th></tr></thead><tbody>{data.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.email||'—'}</td><td className="mono">{c.id.slice(0,12)}</td></tr>)}</tbody></table></section>}
export function Payments({data,onCopy}:{data:Payment[];onCopy:(s:string)=>void}){return <section className="panel"><div className="panelHead"><div><h2>Cobranças</h2><p>Pix, boleto, cartão e links de pagamento.</p></div></div><PaymentTable data={data} onCopy={onCopy}/></section>}
function PaymentTable({data,onCopy}:{data:Payment[];onCopy?:(s:string)=>void}){return <table><thead><tr><th>Cliente</th><th>Descrição</th><th>Método</th><th>Valor</th><th>Status</th><th>Vencimento</th><th></th></tr></thead><tbody>{data.map(p=><tr key={p.id}><td><b>{p.customer.name}</b></td><td>{p.description||'Cobrança'}</td><td>{p.billingType}</td><td>{money(p.amount)}</td><td><span className={`status ${p.status.toLowerCase()}`}>{p.status}</span></td><td>{new Date(p.dueDate).toLocaleDateString('pt-BR')}</td><td>{p.pixPayload&&onCopy&&<button className="icon" title="Copiar Pix" onClick={()=>onCopy(p.pixPayload!)}><Copy size={16}/></button>}</td></tr>)}</tbody></table>}
export function Subscriptions({data}:{data:Subscription[]}){return <section className="panel"><div className="panelHead"><div><h2>Assinaturas recorrentes</h2><p>Cobranças automáticas conforme o ciclo contratado.</p></div></div><table><thead><tr><th>Cliente</th><th>Descrição</th><th>Ciclo</th><th>Método</th><th>Valor</th><th>Próx. vencimento</th><th>Status</th></tr></thead><tbody>{data.map(s=><tr key={s.id}><td><b>{s.customer.name}</b></td><td>{s.description||'Assinatura'}</td><td>{s.cycle}</td><td>{s.billingType}</td><td>{money(s.amount)}</td><td>{new Date(s.nextDueDate).toLocaleDateString('pt-BR')}</td><td><span className={`status ${s.status.toLowerCase()}`}>{s.status}</span></td></tr>)}</tbody></table></section>}
export function PaymentLinks({data,onCopy}:{data:PaymentLink[];onCopy:(s:string)=>void}){return <section className="panel"><div className="panelHead"><div><h2>Links de pagamento</h2><p>Venda por link com Pix, boleto ou cartão.</p></div></div><table><thead><tr><th>Nome</th><th>Tipo</th><th>Método</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>{data.map(l=><tr key={l.id}><td><b>{l.name}</b><small className="subcell">{l.description}</small></td><td>{l.chargeType}</td><td>{l.billingType}</td><td>{l.value?money(l.value):'Livre'}</td><td><span className={`status ${l.active?'received':'cancelled'}`}>{l.active?'ATIVO':'INATIVO'}</span></td><td>{l.url&&<button className="icon" onClick={()=>onCopy(l.url!)}><Copy size={16}/></button>}</td></tr>)}</tbody></table></section>}
export function Transfers({data}:{data:Transfer[]}){return <section className="panel"><div className="panelHead"><div><h2>Transferências Pix</h2><p>Saídas financeiras registradas pelo provedor.</p></div></div><table><thead><tr><th>Destino</th><th>Tipo</th><th>Valor</th><th>Status</th><th>Data</th></tr></thead><tbody>{data.map(t=><tr key={t.id}><td className="mono">{t.pixAddressKey}</td><td>{t.pixAddressKeyType||'PIX'}</td><td>{money(t.amount)}</td><td><span className={`status ${t.status.toLowerCase()}`}>{t.status}</span></td><td>{new Date(t.createdAt).toLocaleString('pt-BR')}</td></tr>)}</tbody></table></section>}
export function Finance({sum}:{sum:Summary|null}){return <div className="grid2"><section className="panel"><h2>Resumo financeiro</h2><div className="financeLine"><span>Recebido</span><b>{money(sum?.balance||0)}</b></div><div className="financeLine"><span>Pendente</span><b>{money(sum?.pending||0)}</b></div><div className="financeLine"><span>Vencido</span><b>{money(sum?.overdue||0)}</b></div></section><section className="panel"><h2>Conciliação automática</h2><div className="empty"><CheckCircle2 size={34}/><b>Webhooks ativos</b><span>Os eventos do provedor atualizam as cobranças e o razão financeiro.</span></div></section></div>}
export function SettingsPanel(){return <section className="panel settings"><h2>Integração financeira</h2><p>Configure as variáveis do backend para alternar entre Sandbox interno e Asaas.</p><code>PAYMENT_PROVIDER=sandbox | asaas</code><code>ASAAS_ENV=sandbox | production</code><code>ASAAS_API_KEY=***</code><p className="hint">Nenhuma credencial sensível deve ser salva no frontend ou no GitHub.</p></section>}
