import {useState,type FormEvent} from 'react';
import {api} from '../api';
import type {Customer} from '../types';
import {Modal} from './Modal';
type Props={close:()=>void;done:()=>void};
export function CustomerModal({close,done}:Props){const[f,setF]=useState({name:'',email:'',phone:'',document:''});const submit=async(e:FormEvent)=>{e.preventDefault();await api('/api/customers',{method:'POST',body:JSON.stringify(f)});done()};return <Modal title="Novo cliente" close={close}><form onSubmit={submit}><label>Nome<input required onChange={e=>setF({...f,name:e.target.value})}/></label><label>E-mail<input type="email" onChange={e=>setF({...f,email:e.target.value})}/></label><label>Telefone<input onChange={e=>setF({...f,phone:e.target.value})}/></label><label>CPF/CNPJ<input onChange={e=>setF({...f,document:e.target.value})}/></label><button className="primary">Cadastrar</button></form></Modal>}
export function PaymentModal({customers,close,done}:{customers:Customer[]}&Props){const[f,setF]=useState({customerId:customers[0]?.id||'',billingType:'PIX',amount:'',dueDate:new Date().toISOString().slice(0,10),description:''});const submit=async(e:FormEvent)=>{e.preventDefault();await api('/api/payments',{method:'POST',body:JSON.stringify(f)});done()};return <Modal title="Nova cobrança" close={close}><form onSubmit={submit}><label>Cliente<select value={f.customerId} onChange={e=>setF({...f,customerId:e.target.value})}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Forma<select value={f.billingType} onChange={e=>setF({...f,billingType:e.target.value})}><option>PIX</option><option>BOLETO</option><option>CREDIT_CARD</option><option>UNDEFINED</option></select></label><label>Valor<input type="number" step="0.01" required onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Vencimento<input type="date" value={f.dueDate} onChange={e=>setF({...f,dueDate:e.target.value})}/></label><label>Descrição<input onChange={e=>setF({...f,description:e.target.value})}/></label><button className="primary" disabled={!f.customerId}>Gerar cobrança</button></form></Modal>}
export function SubscriptionModal({customers,close,done}:{customers:Customer[]}&Props){const[f,setF]=useState({customerId:customers[0]?.id||'',billingType:'PIX',amount:'',nextDueDate:new Date().toISOString().slice(0,10),cycle:'MONTHLY',description:''});const submit=async(e:FormEvent)=>{e.preventDefault();await api('/api/subscriptions',{method:'POST',body:JSON.stringify(f)});done()};return <Modal title="Nova assinatura" close={close}><form onSubmit={submit}><label>Cliente<select value={f.customerId} onChange={e=>setF({...f,customerId:e.target.value})}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Forma<select value={f.billingType} onChange={e=>setF({...f,billingType:e.target.value})}><option>PIX</option><option>BOLETO</option><option>CREDIT_CARD</option><option>UNDEFINED</option></select></label><label>Valor<input type="number" step="0.01" required onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Ciclo<select value={f.cycle} onChange={e=>setF({...f,cycle:e.target.value})}><option>WEEKLY</option><option>BIWEEKLY</option><option>MONTHLY</option><option>BIMONTHLY</option><option>QUARTERLY</option><option>SEMIANNUALLY</option><option>YEARLY</option></select></label><label>Primeiro vencimento<input type="date" value={f.nextDueDate} onChange={e=>setF({...f,nextDueDate:e.target.value})}/></label><label>Descrição<input onChange={e=>setF({...f,description:e.target.value})}/></label><button className="primary" disabled={!f.customerId}>Criar assinatura</button></form></Modal>}
export function PaymentLinkModal({close,done}:Props){const[f,setF]=useState({name:'',description:'',value:'',billingType:'UNDEFINED',chargeType:'DETACHED'});const submit=async(e:FormEvent)=>{e.preventDefault();const body={...f,value:f.value?Number(f.value):undefined};await api('/api/payment-links',{method:'POST',body:JSON.stringify(body)});done()};return <Modal title="Novo link de pagamento" close={close}><form onSubmit={submit}><label>Nome<input required onChange={e=>setF({...f,name:e.target.value})}/></label><label>Descrição<input onChange={e=>setF({...f,description:e.target.value})}/></label><label>Valor opcional<input type="number" step="0.01" onChange={e=>setF({...f,value:e.target.value})}/></label><label>Forma<select value={f.billingType} onChange={e=>setF({...f,billingType:e.target.value})}><option>UNDEFINED</option><option>PIX</option><option>BOLETO</option><option>CREDIT_CARD</option></select></label><label>Tipo<select value={f.chargeType} onChange={e=>setF({...f,chargeType:e.target.value})}><option>DETACHED</option><option>RECURRENT</option><option>INSTALLMENT</option></select></label><button className="primary">Criar link</button></form></Modal>}
